"""add event on review model

Revision ID: dd9f35204a63
Revises: 7dc6fefd17d0
Create Date: 2025-04-16 19:22:09.094489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd9f35204a63'
down_revision: Union[str, None] = '7dc6fefd17d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events_on_review', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.drop_constraint('events_on_review_user_id_fkey', 'events_on_review', type_='foreignkey')
    op.create_foreign_key(None, 'events_on_review', 'users', ['creator_id'], ['id'])
    op.drop_column('events_on_review', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events_on_review', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'events_on_review', type_='foreignkey')
    op.create_foreign_key('events_on_review_user_id_fkey', 'events_on_review', 'users', ['user_id'], ['id'])
    op.drop_column('events_on_review', 'creator_id')
    # ### end Alembic commands ###
